project:
  type: website

website:
  navbar:
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contribution.qmd
      - text: "Meeting Minutes"
        href: minutes/index.qmd
      - Conferences.qmd
      - text: "White Paper"
        href: "https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/DVOST/%2328798+Phuse+White+Paper+-+WP-077+Jun+2023+v2.pdf"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

