project:
  type: website
  output-dir: docs

website:
  title: "CAMIS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
execute:
  freeze: auto
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

