project:
  type: website

website:
  navbar:
    logo: "images/logo.png"
    tools:
      - icon: github
        menu:
            - text: Source Code
              url:  https://github.com/PSIAIMS/CAMIS/
            - text: Report a Bug
              url:  https://github.com/PSIAIMS/CAMIS/issues/
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contribution.qmd
      - text: "Meeting Minutes"
        href: minutes/index.qmd
      - Conferences.qmd
      - text: "White Paper"
        href: "https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Data+Visualisation+%26+Open+Source+Technology/WP077.pdf"
      

format:
  html:
    toc: true
    theme:
      light: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css


editor: visual

