on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Put pandoc in PATH
        run: |
          mkdir -p ~/.local/bin
          ln -s $(dirname $(readlink -f  $(which quarto)))"/pandoc" ~/.local/bin/pandoc
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Build site 🔧
        run: |
          quarto render
      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
    # steps:
    #   - name: Check out repository
    #     uses: actions/checkout@v3
    #     
    #   - name: Set up Quarto
    #     uses: quarto-dev/quarto-actions/setup@v2
    #     with:
    #       # To install LaTeX to build PDF book 
    #       tinytex: true 
    #       # uncomment below and fill to pin a version
    #       # version: 0.9.600
    #   
    #   - name: Install lib curl
    #     if: runner.os == 'Linux'
    #     run: |
    #       sudo apt-get install libcurl4-openssl-dev
    #       
    #   - name: Setup dependencies
    #     run: |
    #       R -e 'install.packages("curl")' 
    #       R -e 'install.packages("renv")' 
    #       R -e 'renv::restore()'
    # 
    #   - name: Publish to GitHub Pages (and render)
    #     uses: quarto-dev/quarto-actions/publish@v2
    #     with:
    #       target: gh-pages
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
