on:
  pull_request:
    branches: main

name: Test Rendering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Install Python deps"
        run: |
          pip install -r requirements.txt

      - name: Install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          # http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          r-version: 'renv'

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with: 
          cache-version: 3

      - name: Build site 🔧
        run: |
          quarto render
    